In [1]:
from py.tap_trial import tap_trial

import numpy as np
import pandas as pd

net_filename = 'SiouxFalls_net.tntp'

# Optimizing inputs to a gravity model used to construct and OD matrix

Compared against "ground truth" flows from a reference OD matrix.

In [2]:
true_flows = pd.read_pickle('py/gravity_model/true_flows.pkl')
true_flows

flow       cost       der
link                                      
(1,2)     4494.611949   6.000816  0.000001
(1,3)     8119.023795   4.008691  0.000004
(2,1)     4519.023795   6.000834  0.000001
(2,6)     5967.349609   6.573612  0.001055
(3,1)     8094.611949   4.008586  0.000004
...               ...        ...       ...
(23,22)   9626.204795  12.243120  0.003425
(23,24)   7902.825870   3.759163  0.000890
(24,13)  11112.223948  17.616184  0.004901
(24,21)  10259.521627  11.752569  0.003412
(24,23)   7861.825123   3.722940  0.000877

[76 rows x 3 columns]

In [3]:
odm = tap_trial(netFileName=net_filename, true_flows=true_flows, skip_solving=True, params=np.ones(276))#np.arange(1,277))
odm

array([[0.00000000e+00, 1.12776821e+03, 8.35598481e+02, 9.79717426e+02,
        2.10431410e+02, 2.12043182e+02, 2.03140395e+02, 4.21388698e+02,
        2.45598654e+02, 6.02619441e+02, 5.34676686e+02, 1.09093290e+03,
        6.95908942e+02, 2.08583296e+02, 1.36645891e+02, 2.02205901e+02,
        1.50229903e+02, 3.93316224e+01, 6.60777988e+01, 2.29798068e+02,
        9.82237188e+01, 1.98537417e+02, 2.05333360e+02, 1.05208601e+02],
       [1.12568748e+03, 0.00000000e+00, 4.72045049e+01, 1.82962152e+02,
        9.17257705e+01, 3.62356034e+02, 1.83612431e+02, 5.13144089e+02,
        9.95447250e+01, 2.69286143e+02, 1.28031048e+02, 1.25773100e+02,
        1.02874033e+02, 5.41067900e+01, 7.06986092e+01, 1.60635736e+02,
        1.08249557e+02, 3.12456959e+01, 4.41089568e+01, 1.53397257e+02,
        2.32157033e+01, 6.35813275e+01, 3.96065950e+01, 1.89522596e+01],
       [8.36899464e+02, 4.73653889e+01, 0.00000000e+00, 4.57193010e+02,
        6.81941030e+01, 2.99328757e+01, 2.69645079e+01, 5.7696

In [4]:
odm.max()

10478.813930592893

In [5]:
odm.min()

0.0

In [6]:
odm.sum(axis=0)

array([ 8800.        ,  4000.        ,  2800.        , 11600.        ,
        6100.        ,  7600.        , 12100.        , 16700.00000001,
       16200.        , 45200.00000001, 22300.        , 13899.99999999,
       14599.99999999, 14100.        , 21400.        , 26100.00000001,
       23400.00000001,  4800.        , 12800.        , 18500.        ,
       11000.        , 24399.99999999, 14499.99999999,  7700.        ])

In [7]:
odm.sum(axis=1)

array([ 8800.,  4000.,  2800., 11700.,  6100.,  7600., 12100., 16700.,
       16300., 45100., 22400., 14000., 14500., 14100., 21300., 26100.,
       23400.,  4700., 12800., 18400., 11000., 24400., 14500.,  7800.])

In [8]:
rmse = tap_trial(netFileName=net_filename, true_flows=true_flows, params=np.ones(276))#np.arange(1,277))
rmse

Empty DataFrame
Columns: [flow, cost, der]
Index: []


ValueError: zero-size array to reduction operation maximum which has no identity